//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Gameoverpanel_prefab
    {
        public const string BundleName = "gameoverpanel_prefab";
        public const string GAMEOVERPANEL = "GameOverPanel";
    }
    public class Gamepanel_prefab
    {
        public const string BundleName = "gamepanel_prefab";
        public const string GAMEPANEL = "GamePanel";
    }
    public class Gamepasspanel_prefab
    {
        public const string BundleName = "gamepasspanel_prefab";
        public const string GAMEPASSPANEL = "GamePassPanel";
    }
    public class Gamestartpanel_prefab
    {
        public const string BundleName = "gamestartpanel_prefab";
        public const string GAMESTARTPANEL = "GameStartPanel";
    }
}
